### ISSUE TITLE
Ability to use without the TUI

### ISSUE THREAD

**Issue by dlvhdr** [poetaman/arttime#37]
I would like to embed a random art in my terminal text editor - neovim.
Is it possible to add an option to run this without the TUI - just the output of a random art?

**Comment by poetaman** [comment]
@dlvhdr arttime comes with artprint to  ``artprint --help``. From the documentation:

```
    Why artprint? To provide a consistent display of text art in multiple
    applications. While artprint is a program in the arttime repository and
    used by arttime to print art on screen, is not tied or limited
    to arttime. One can use artprint to bring the beauty of text art
    to various aspects of their development environment, without having
    to reinvent the wheel.
```

**Comment by dlvhdr** [comment]
Yes perfect, thank you!

**Comment by poetaman** [comment]
@dlvhdr Given you mentioned "random art", you might also be interested in a new option ``--random`` that works with both ``arttime`` and ``artprint``. Enjoy!

**Comment by poetaman** [comment]
Update: ``--random`` requires a value in [v1.9.8](https://github.com/poetaman/arttime/releases/tag/v1.9.8). For original behavior, do ``--random notarot``. Here's the snippet from ``arttime --help``:

```
    --random [all|tarot|notarot]
                select and display a random art from arttime's collection
                Meaning of value passed:
                    all     : select from pool of all art files
                    tarot   : select from only tarot art files
                    notarot : select from all art except tarot
                When passed, user should not pass option -a or -b
```
