### ISSUE TITLE
Feature request: Support bash

### ISSUE THREAD

**Issue by Sayanel01** [poetaman/arttime#40]
I there a feature that is specific of zsh and can't work with bash?

**Comment by poetaman** [comment]
@Sayanel01 arttime can be launched from any shell bash/csh/zsh/ksh/etc, it just requires zsh to be installed on the system. While basic operations in bash and zsh have same or similar syntax, zsh is mostly a superset of bash (check one example below). My code will get 20-30% longer and less performant if I were to recode every line to be bash compatible. I don't see value in it. All Linux users need to do is install a zsh package, i.e. run just one command from their shell, like: ``sudo apt install zsh``. On Debian, the install size is 2MB, are we suggesting that we want to save 2MB of disk space in 21st century? They don't need to change their shell, which is what matters the most to users, and takes time.

Just 1 example of why zsh over bash: Let's say you need to check version number in your software (version number compare is not as simple as float or integer compare), zsh comes with a function ``is-at-least``. To achieve the same result in bash would require 20-30 lines of bash code (google it). There are plenty of examples I can write, though I would leave it for a blog for some other time.
