### ISSUE TITLE
Not working properly in i3

### ISSUE THREAD

**Issue by awelormro** [poetaman/arttime#55]
The main issue is the fact that is not showing popup notifications in i3, also the sound sometimes is not working, how can I check the way arttime launches the system notifications?

**Comment by poetaman** [comment]
There are two things that can cause notifications to not work on Linux:
1. ``notify-send`` is not installed. Check that by running ``command -v notify-send``.  If it doesn't return a valid path, you would first have to install ``notifiy-send``. The name of the package varies by Linux desktop environment.
2. ``notify-send`` is installed but ``notify-send "Hello world"`` does not give any notification. In that case, you perhaps don't have a notification daemon running. Search the web on how to install and enable some notification daemon on i3. Here's an example discussion on notification servers on [i3wm subreddit](https://www.reddit.com/r/i3wm/comments/opas9h/notifysend_doesnt_do_anything_arch/).

**Comment by awelormro** [comment]
Thanks! it was a conflict with notify-send old version, now it works well! and it's amazing, but now i have a question about the usage, to invoke it remotely, can I post it here, shall I need to open a new issue or it's still not implemented the remote call?

**Comment by poetaman** [comment]
@awelormro Awesome! you are welcome. Can you please paste a screenshot of how it looks like on i3 with i3 notification/s? A new issue would make most sense. Not sure what you mean by invoking it remotely, it would be good to have a new issue with clear description of intended usage.

**Comment by awelormro** [comment]
I'm working with a fork called i3-rounded-gaps, and it works with dunst, I haven' noticed the fact that in this version some notifications aren't working, not only arttime... but when I've reinstalled dunst not only arttime started to work, cannot talk for every user, and also, I  use a forked fork and maybe that might break some dependencies, but here you go, here's a notification example :) 
![Captura de pantalla_2023-05-17_19-24-40](https://github.com/poetaman/arttime/assets/73954341/5ef8f737-963c-49bd-8f3a-e20bd55979d4)
